export const tokenKey     = 'Token'

export const urlSignup    = 'http://localhost:18080/api/signup'
export const urlIsLogin   = 'http://localhost:18080/api/is_login'
export const urlLogin     = 'http://localhost:18080/api/login'
export const urlLogout    = 'http://localhost:18080/api/logout'

export const token        = 'token'
export const isLogin      = 'isLogin'
export const init         = 'init'
export const signup       = 'signup'
export const login        = 'login'
export const logout       = 'logout'
export const modalName    = 'modalName'
export const modalContent = 'modalContent'
export const updateModal  = 'updateModal'

export const modalNone    = ''
export const modalMessage = 'Message'
export const modalSignup  = 'Signup'
export const modalLogin   = 'Login'
