export const tokenKey = 'Token'

export const urlSignup        = 'http://localhost:18080/api/signup'
export const urlIsLogin       = 'http://localhost:18080/api/is_login'
export const urlLogin         = 'http://localhost:18080/api/login'
export const urlLogout        = 'http://localhost:18080/api/logout'
export const urlGetUsers      = 'http://localhost:18080/api/get_users'     
export const urlGetMicroposts = 'http://localhost:18080/api/get_microposts'
export const urlPostMicropost = 'http://localhost:18080/api/post_micropost'
export const urlGetFollowees  = 'http://localhost:18080/api/get_followees' 
export const urlGetFollowers  = 'http://localhost:18080/api/get_followers' 
export const urlFollow        = 'http://localhost:18080/api/follow'        
export const urlUnfollow      = 'http://localhost:18080/api/unfollow'      

export const token         = 'token'
export const isLogin       = 'isLogin'
export const init          = 'init'
export const signup        = 'signup'
export const login         = 'login'
export const logout        = 'logout'
export const getUsers      = 'getUsers'
export const getMicroposts = 'getMicroposts'
export const postMicropost = 'postMicropost'
export const getFollowees  = 'getFollowees'
export const getFollowers  = 'getFollowers'
export const follow        = 'follow'
export const unfollow      = 'unfollow'
export const modalName     = 'modalName'
export const modalContent  = 'modalContent'
export const updateModal   = 'updateModal'

export const modalNone    = ''
export const modalMessage = 'Message'
export const modalSignup  = 'Signup'
export const modalLogin   = 'Login'

export const timeout = 500
